GIVEAWAY_DETECTED = "detected"
GIVEAWAY_PARSED = "parsed"
GIVEAWAY_READY = "ready"
GIVEAWAY_EXECUTING = "executing"
GIVEAWAY_SUCCESS = "success"
GIVEAWAY_PARTIAL = "partial_or_failed"
GIVEAWAY_FAILED = "failed"
GIVEAWAY_NEEDS_HUMAN = "needs_human"
GIVEAWAY_RETRY_REQUESTED = "retry_requested"
GIVEAWAY_SKIPPED = "skipped"

VALID_STATUSES = {
    GIVEAWAY_DETECTED,
    GIVEAWAY_PARSED,
    GIVEAWAY_READY,
    GIVEAWAY_EXECUTING,
    GIVEAWAY_SUCCESS,
    GIVEAWAY_PARTIAL,
    GIVEAWAY_FAILED,
    GIVEAWAY_NEEDS_HUMAN,
    GIVEAWAY_RETRY_REQUESTED,
    GIVEAWAY_SKIPPED,
}
